export const FETCH_PRODUCTS_SUCCESS='FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR='FETCH_PRODUCTS_ERROR';
export const FETCH_CATEGORIES_SUCCESS='FETCH_CATEGORIES_SUCCESS';
export const FETCH_ONE_PRODUCT_SUCCESS='FETCH_ONE_PRODUCT_SUCCESS';
export const FETCH_ONE_CATEGORY='FETCH_ONE_CATEGORY';

export const REGISTRER_USER_FAIL='REGISTRER_USER_FAIL';
export const REGISTRER_USER_SUCCESS='REGISTRER_USER_SUCCESS';
export const LOGIN_USER_SUCCESS='LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL='LOGIN_USER_FAIL';
export const LOGOUT_USER='LOGOUT_USER';